ARG PYTHON_VERSION=3.12
FROM python:$PYTHON_VERSION-slim

WORKDIR /app

# install tools
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  cmake \
  git \
  bison \
  flex \
  libboost-all-dev \
  curl \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

# install uv
RUN curl -LsSf https://astral.sh/uv/0.5.26/install.sh | sh

# install staq
WORKDIR /tmp/staq
RUN git clone https://github.com/softwareQinc/staq.git . \
  && mkdir build \
  && cd build \
  && cmake .. \
  && make -j$(nproc) \
  && make install \
  && rm -rf /tmp/staq

# copy
WORKDIR /app
COPY . /app
