ARG PYTHON_VERSION=3.12
FROM python:$PYTHON_VERSION-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

# install tools
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  cmake \
  bison \
  flex \
  libboost-all-dev \
  curl \
  git \
  iproute2 \
  procps \
  tar \
  vim && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

# install staq
WORKDIR /tmp/staq
RUN git clone https://github.com/softwareQinc/staq.git . \
  && mkdir build \
  && cd build \
  && cmake .. \
  && make -j$(nproc) \
  && make install \
  && rm -rf /tmp/staq
WORKDIR /app

# setup user
RUN adduser --disabled-password --gecos "" appuser && chown -R appuser:appuser /app
USER appuser

COPY . /app

# install python dependencies
RUN uv sync

# run application
CMD ["uv", "run", "python", "src/tranqu_server/proto/service.py", "-c", "config/config.yaml", "-l", "config/logging.yaml"]
