# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tranqu_server.proto.v1 import tranqu_pb2 as tranqu__server_dot_proto_dot_v1_dot_tranqu__pb2


class TranspilerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transpile = channel.unary_unary(
                '/tranqu_server.proto.v1.TranspilerService/Transpile',
                request_serializer=tranqu__server_dot_proto_dot_v1_dot_tranqu__pb2.TranspileRequest.SerializeToString,
                response_deserializer=tranqu__server_dot_proto_dot_v1_dot_tranqu__pb2.TranspileResponse.FromString,
                _registered_method=True)


class TranspilerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transpile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranspilerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transpile': grpc.unary_unary_rpc_method_handler(
                    servicer.Transpile,
                    request_deserializer=tranqu__server_dot_proto_dot_v1_dot_tranqu__pb2.TranspileRequest.FromString,
                    response_serializer=tranqu__server_dot_proto_dot_v1_dot_tranqu__pb2.TranspileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tranqu_server.proto.v1.TranspilerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tranqu_server.proto.v1.TranspilerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranspilerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transpile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tranqu_server.proto.v1.TranspilerService/Transpile',
            tranqu__server_dot_proto_dot_v1_dot_tranqu__pb2.TranspileRequest.SerializeToString,
            tranqu__server_dot_proto_dot_v1_dot_tranqu__pb2.TranspileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
