# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tranqu_server/proto/v1/tranqu.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tranqu_server/proto/v1/tranqu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#tranqu_server/proto/v1/tranqu.proto\x12\x16tranqu_server.proto.v1\"\xf9\x01\n\x10TranspileRequest\x12\x1d\n\nrequest_id\x18\x01 \x01(\tR\trequestId\x12\x18\n\x07program\x18\x02 \x01(\tR\x07program\x12\x1f\n\x0bprogram_lib\x18\x03 \x01(\tR\nprogramLib\x12%\n\x0etranspiler_lib\x18\x04 \x01(\tR\rtranspilerLib\x12-\n\x12transpiler_options\x18\x05 \x01(\tR\x11transpilerOptions\x12\x16\n\x06\x64\x65vice\x18\x06 \x01(\tR\x06\x64\x65vice\x12\x1d\n\ndevice_lib\x18\x07 \x01(\tR\tdeviceLib\"\xaa\x01\n\x11TranspileResponse\x12\x16\n\x06status\x18\x01 \x01(\rR\x06status\x12-\n\x12transpiled_program\x18\x02 \x01(\tR\x11transpiledProgram\x12\x14\n\x05stats\x18\x03 \x01(\tR\x05stats\x12\x38\n\x18virtual_physical_mapping\x18\x04 \x01(\tR\x16virtualPhysicalMapping2w\n\x11TranspilerService\x12\x62\n\tTranspile\x12(.tranqu_server.proto.v1.TranspileRequest\x1a).tranqu_server.proto.v1.TranspileResponse\"\x00\x42\x9f\x01\n\x1a\x63om.tranqu_server.proto.v1B\x0bTranquProtoP\x01\xa2\x02\x03TPX\xaa\x02\x15TranquServer.Proto.V1\xca\x02\x15TranquServer\\Proto\\V1\xe2\x02!TranquServer\\Proto\\V1\\GPBMetadata\xea\x02\x17TranquServer::Proto::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tranqu_server.proto.v1.tranqu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.tranqu_server.proto.v1B\013TranquProtoP\001\242\002\003TPX\252\002\025TranquServer.Proto.V1\312\002\025TranquServer\\Proto\\V1\342\002!TranquServer\\Proto\\V1\\GPBMetadata\352\002\027TranquServer::Proto::V1'
  _globals['_TRANSPILEREQUEST']._serialized_start=64
  _globals['_TRANSPILEREQUEST']._serialized_end=313
  _globals['_TRANSPILERESPONSE']._serialized_start=316
  _globals['_TRANSPILERESPONSE']._serialized_end=486
  _globals['_TRANSPILERSERVICE']._serialized_start=488
  _globals['_TRANSPILERSERVICE']._serialized_end=607
# @@protoc_insertion_point(module_scope)
